#!groovy

pipeline {
    agent {
        label 'ubuntu' 
    }
    stages {
        stage("create docker image") {
            steps {
                echo "=======starting building image====="
                dir ('task3') {
                    sh 'docker build -t novogrodsky/nginx-ubuntu:latest .'
                }    
            }
        }
    }
}
