#!groovy
// Check ub1 properties
properties([disableConcurrentBuilds()])

pipeline {
    agent {
        label 'slave-host' 
    }
    stages {
        stage("create docker image") {
            steps {
                echo "=======starting building image====="
                dir ('task3')
                sh 'docker build .'
            }
        }
    }
}
